language: ruby
node_js:
- '7'
cache: bundler
branches:
  only:
  - master

before_install:
- rvm install 2.2
- rvm use 2.2
- ". $HOME/.nvm/nvm.sh && nvm install 6.1 && nvm use 6.1"
- gem install bundler
- bundle check || bundle install
install:
- npm install -g firebase-tools
script:
- set -e
- jekyll build
after_success:
- firebase deploy --token "$FIREBASE_TOKEN"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
