language: ruby
node_js:
- '7'
cache: bundler
branches:
  only:
  - master
before_install:
- rvm install 2.2
- rvm use 2.2
- ". $HOME/.nvm/nvm.sh && nvm install 6.1 && nvm use 6.1"
- gem install bundler
- bundle check || bundle install
install:
- npm install -g firebase-tools
script:
- set -e
- jekyll build
after_success:
- firebase deploy --token "$FIREBASE_TOKEN"
notifications:
  slack:
    secure: I5jn6bxphaY74j/Hy0AvyTXmuT956KUT7TpOPSZ26Vt4qlq7IkKESgxhfPp8kEJ+R+PBgQdzNSjDQPKkuxB3iy/Iz4eNAiXtc8LhBz7Pp5aXIQMgWLmmzVxjiLi6mP7g+MqPCZ9T9JFLDt6Ddio7ilM+ZTzx1lFBcN1pFhLxx2KZfc4UDHmz0t49d4kI3/YWAFKDPilvPXf4JxJLmR7spmD7vXtCsnt2aqZH/y1QHjTctCMIT/e96SPV0zQ6mkrlbKPmxhc1uqynMOtlGJNR+4rIekBowUeoCyjWvWvmleVyDuegVxJ3J51EMrOFxjxkmyrm/qmHbtN8DCc8uv9Jsc94EMoe1JoEb1xI6kyHP8Ty8tQlow8WcSNXpUO/IB47w5FRT/FSbXq0+hr0XJqdr2xOCtz3nAE+JONKil49v4Jy+dItXkBgpYH8bdKlwQXTTOoDIhgizbL402CtLUb58jS9K5t/N3Q4rg29wMVMfOE0pvxjKu2Y+94l/1HsqIn9viiuo3PjdlwXZL+B09tNLmr4JQNwNchLZ8DrkVY27ATIXD461Zxuvf4MK8/0ZH4KBxLriW6pNal3VEMf7giomkreBeDrwUmsG22jq3RZiNQ0frJ2NSBtn1fBJX2/NFag99/WObGxJJiWKM+ZA2znvYXImgoA170Y9fstgpKz/Kg=
